### ISSUE TITLE
Love to See your Efforts

### ISSUE THREAD

**Issue by afzl-wtu** [PeterNjeim/MagiskOnWSA#2]
I was watching your issues and comments on official MagiskOnWSA repo. I was disappointed to see how your issues are closed without resolving them. But now I am glad to see you did not give up and started to provide your own build with gapps on your repo. Thanks a lot. From now on I am your fan.

**Comment by afzl-wtu** [comment]
Also it would be great if you reply to this comment:
https://github.com/LSPosed/MagiskOnWSA/issues/402

**Comment by PeterNjeim** [comment]
Thanks for the comment, and I have left a reply to your comment.

**Comment by PeterNjeim** [comment]
For the future, GitHub has a Discussions tab, use that for dicussing non-code-related issues, thanks
